@startuml Classes

class RequestBody {
    + {abstract} getContentTypeHeader(): string
    + {abstract} getBody(): string
    + {abstract} getSize(): size_t
}
hide RequestBody fields

class FormdataRequestBody {
    - boundary: string
    - body: map<string, sting>

    + FormdataRequestBody(boundary: string)
    + FormdataRequestBody()
    + addElement(key: string, value: string): void
    + addFile(key: string, filePath: string): void
}

class RawRequestBody {
    - contentTypeHeader: string
    - body: string

    + RawRequestBody(contentTypeHeader: string)
    + RawRequestBody()
    + setBody(body: string): void
}

class Response {
    + statusCode: int
    + headers: map<string, string>
    + body: string
}
hide Response methods

class Request {
    - method: string
    - uri: string
    - headers: map<string, string>
    - body: RequestBody

    + Request(method: string, uri: string)
    + addHeader(header: string, value: string): void
    + setBody(body: RequestBody): void
    + send(callback(response: response): function<void>): void
}

@enduml