@startuml Classes

enum HttpRequestMethod {
    DELETE,
    GET,
    HEAD,
    OPTIONS,
    PATCH,
    POST,
    PUT
}
hide HttpRequestMethod methods

class FormdataElement {
    + name: std::string
    + value: std::variant<std::string, std::FILE>
}
hide FormdataElement methods

abstract class Request {
    # requestMethod: HttpRequestMethod
    # uri: std::string
    # body: std::variant<std::list<FormdataElement>, std::string>

    + setBody(body: std::variant<std::list<FormdataElement>, std::string>): void
    + {abstract} Request(method: HttpRequestMethod, uri: std::string)
    + {abstract} addHeader(header: std::string, value: std::string): void
    + {abstract} addCookie(cookie: std::string, value: std::string): void
    + {abstract} send();
}

class CprRequest
hide CprRequest fields
hide CprRequest methods

@enduml